# email_client.py

from typing import Optional, Tuple, List, Dict, Any

class EmailClient:
    def search(self, query) -> Optional[Tuple[List[Dict], Optional[str], int]]: ...
    def fetch_headers(self, message_id) -> Dict[str, Any]: ...
    def fetch_preview(self, message_id) -> Optional[str]: ...
    def download_eml(self, message_id, filename): ...