# email_client.py

class EmailClient:
    def search(self, query): ...
    def fetch_headers(self, message_id): ...
    def fetch_preview(self, message_id): ...
    def download_eml(self, message_id, filename): ...